name: AIO-Jetpacks
main: de.freestylecrafter.aio.jetpacks.AIOPlugin
version: ${project.version}
commands:
    jetpacks:
        description: AIO Jetpacks help
        usage: /jetpacks
        permission: aio.jetpacks.command.base
    jp:
        aliases: [jetpack]
        description: Enable/disable your jetpack
        usage: /jp
        permission: aio.jetpacks.command.base
permissions:
    aio.jetpacks.command.base:
        description: Allows you to use /jetpacks
        default: op
